# Generated by h2py from /usr/local/google/buildbot/src/android/ndk-release-r17/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/include/stddef.h
__WCHAR_TYPE__ = int
NULL = 0
